baseURL = "https://Ming-Ta.github.io/"
languageCode = "zh-tw"
title = "Ming-Ta ?券收??閮"
canonifyURLs = true
theme = "PaperMod"
canonifyURLs = true  # ?啣???銵?
[params]
  homeInfoParams = {Title = "?? ?券收??4 閮毀閮", Content = "?格?嚗?026撟游?鞈賣???3:59:59"}
  ShowReadingTime = true
  ShowPostNavLinks = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Ming-Ta"

[menu]
  [[menu.main]]
    name = "閮毀?亥?"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "?"
    url = "/about/"
    weight = 2
# updated

# updated
